// actionTypes.ts
export const POST_GAME_REQUEST = 'POST_GAME_REQUEST';
export const POST_GAME_SUCCESS = 'POST_GAME_SUCCESS';
export const POST_GAME_FAILURE = 'POST_GAME_FAILURE';
export const SAVE_PLAYER_NAMES_FAILURE = 'SAVE_PLAYER_NAMES_FAILURE';
export const SAVE_PLAYER_NAMES_SUCCESS = 'SAVE_PLAYER_NAMES_SUCCESS';
export const SAVE_PLAYER_NAMES_REQUEST = 'SAVE_PLAYER_NAMES_REQUEST';